language: python

python:
  - 3.6

install:
  - pip install coveralls pycodestyle pyyaml
  - python setup.py install

script:
  - coverage run --source=blameandshame setup.py test

after_success:
  - coveralls
